### ISSUE TITLE
kubectl create crd error (hashtag123167)

### ISSUE THREAD

**Issue by vikramsubramanian** [Mayil-AI-Sandbox/kubernetes#21]
hashtaghashtaghashtag What happened?

i have define the crd param
```
extra_data:
  type: object
  additionalProperties:
    additionalProperties: true
    x-kubernetes-preserve-unknown-fields: true
```

but when i apply the yaml it reports unknown field 

```
extra_data:
  service_data:
    replicas: 1
    volumes_from_cm:
      - cm_name: "sample-conf"
        mount_path: "/data/config"
```

but i can create this yaml
```
extra_data:
  service_data:
    - external_name: test-db
       external_host:
        - key: "123"
          value: "test"
          obj:
            key1: val1
            key2: val2
            key3: val3
      external_pkort: 3306
      gateway_port: 80
```

hashtaghashtaghashtag What did you expect to happen?

create success

hashtaghashtaghashtag How can we reproduce it (as minimally and precisely as possible)?

try it in any crd

hashtaghashtaghashtag Anything else we need to know?

_No response_

hashtaghashtaghashtag Kubernetes version

<details>

```console
$ kubectl version

Client Version: v1.28.2
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.26.1-tke.2
WARNING: version difference between client (1.28) and server (1.26) exceeds the supported minor version skew of +/-1
```

</details>

hashtaghashtaghashtag Cloud provider

<details>
tencentcloud
</details>

hashtaghashtaghashtag OS version

<details>

```console
hashtag On Linux:
$ cat /etc/os-release
hashtag paste output here
$ uname -a
hashtag paste output here

hashtag On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
hashtag paste output here
```

</details>

hashtaghashtaghashtag Install tools

<details>

</details>

hashtaghashtaghashtag Container runtime (CRI) and version (if applicable)

<details>

</details>

hashtaghashtaghashtag Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

)
