### ISSUE TITLE
Accessing NodePort on K8S host has latency when reaching Pods across different hosts (hashtag122835)

### ISSUE THREAD

**Issue by vikramsubramanian** [Mayil-AI-Sandbox/kubernetes#51]
hashtaghashtaghashtag What happened?

I have deployed a Kubernetes cluster on Debian 12.4 operating system. I am using a test image, exposing a port to obtain the container's name. I use this method to determine which Pod the request is assigned to.

As shown in the screenshot below, accessing the Pod on the local machine works fine. However, if the request is assigned to a Pod on another host, there is a 1-second delay before receiving a response. Upon inspecting the packets using tcpdump, I observed that the first request resulted in a connection reset, and I am not quite sure about the cause of this issue.

![image](

![image](

hashtaghashtaghashtag What did you expect to happen?

Deployed Kubernetes environment is functioning properly on CentOS 7.9 operating system.

![image](

hashtaghashtaghashtag How can we reproduce it (as minimally and precisely as possible)?

I can reproduce it on Debian 12, Debian 11, and Ubuntu 22.04.

Here is my YAML file.

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: test
  template:
    metadata:
      labels:
        app: test
    spec:
      containers:
      - name: test
        image: centos:7.9.2009
        command:
        - sh
        - -c
        - |
          echo $(hostname) > hostname.txt
          python -m SimpleHTTPServer
        resources:
          limits:
            memory: 512Mi
            cpu: 1
          requests:
            memory: 64Mi
            cpu: 0.01
        volumeMounts:
        - name: tz-config
          mountPath: /etc/localtime
      volumes:
      - name: tz-config
        hostPath:
          path: /usr/share/zoneinfo/Etc/GMT-8

---

apiVersion: v1
kind: Service
metadata:
  name: test
  namespace: default
spec:
  selector:
    app: test
  ports:
  - name: external-test
    port: 8000
    targetPort: 8000
    nodePort: 8000
  type: NodePort

```

hashtaghashtaghashtag Anything else we need to know?

_No response_

hashtaghashtaghashtag Kubernetes version

<details>

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.4", GitCommit:"872a965c6c6526caa949f0c6ac028ef7aff3fb78", GitTreeState:"clean", BuildDate:"2022-11-09T13:36:36Z", GoVersion:"go1.19.3", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.4", GitCommit:"872a965c6c6526caa949f0c6ac028ef7aff3fb78", GitTreeState:"clean", BuildDate:"2022-11-09T13:29:58Z", GoVersion:"go1.19.3", Compiler:"gc", Platform:"linux/amd64"}

```
</details>

hashtaghashtaghashtag Cloud provider

<details>
Aliyun
</details>

hashtaghashtaghashtag OS version

<details>

```console
hashtag On Linux:
$ cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 12 (bookworm)"
NAME="Debian GNU/Linux"
VERSION_ID="12"
VERSION="12 (bookworm)"
VERSION_CODENAME=bookworm
ID=debian
HOME_URL="
SUPPORT_URL="
BUG_REPORT_URL="
$ uname -a
Linux debian-1 6.1.0-16-amd64 hashtag1 SMP PREEMPT_DYNAMIC Debian 6.1.67-1 (2023-12-12) x86_64 GNU/Linux


hashtag On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
hashtag paste output here
```

</details>

hashtaghashtaghashtag Install tools

<details>

</details>

hashtaghashtaghashtag Container runtime (CRI) and version (if applicable)

<details>
containerd -v
containerd containerd.io 1.6.27 a1496014c916f9e62104b33d1bb5bd03b0858e59

</details>

hashtaghashtaghashtag Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>
mirrored-flannelcni-flannel:v0.20.1
</details>

)
